[package]
name = "elm-rust-binding"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyscript = { version = "0.9.0", features = ["console"] }
serde = { version = "1.0.215", features = ["derive"] }
serde-reflection = "0.4.0"
uuid = { version = "1.11.0", features = ["v7"] }
